name: Update Index Test

on:
  workflow_dispatch: # Позволяет запускать workflow вручную

jobs:
  build:
    runs-on: ubuntu-latest # Указываем операционную систему для запуска

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Клонируем репозиторий

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Dispatch organization event
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_PAT }} # Используем PAT вместо стандартного токена
        with:
          script: |
            await github.request('POST /repos/{owner}/{repo}/dispatches', {
              owner: '${{ github.repository_owner }}',
              repo: 'index',
              event_type: 'package_released',
              client_payload: {
                repository: '${{ github.repository }}',
                tag: '${{ github.ref_name }}'
              }
            });
